Repository benjisoft/Archivord, pull requests merged in 2023-12, with the labels that each got.

#6 Adding base UI
  Archivord.UI/.eslintrc.cjs
  Archivord.UI/.gitignore
  Archivord.UI/README.md
  Archivord.UI/index.html
  Archivord.UI/package-lock.json
  Archivord.UI/package.json
  Archivord.UI/public/vite.svg
  Archivord.UI/src/App.css
  Archivord.UI/src/App.tsx
  Archivord.UI/src/assets/react.svg
  Archivord.UI/src/components/ChannelCard.tsx
  Archivord.UI/src/components/GuildAvatar.tsx
  Archivord.UI/src/components/ServerCard.tsx
  Archivord.UI/src/constants/permissonContants.ts
  Archivord.UI/src/helpers/api.ts
  Archivord.UI/src/helpers/colourHelper.ts
  Archivord.UI/src/helpers/getAuthUrl.ts
  Archivord.UI/src/helpers/getToken.ts
  Archivord.UI/src/helpers/permissionsHelper.ts
  Archivord.UI/src/helpers/stringHelper.ts
  Archivord.UI/src/index.css
  Archivord.UI/src/interfaces/Channel.ts
  Archivord.UI/src/interfaces/Guild.ts
  Archivord.UI/src/interfaces/GuildPreview.ts
  Archivord.UI/src/main.tsx
  Archivord.UI/src/pages/Archive.tsx
  Archivord.UI/src/pages/Authorize.tsx
  Archivord.UI/src/pages/Authorized.tsx
  Archivord.UI/src/pages/ChannelArchive.tsx
  Archivord.UI/src/pages/GuildArchive.tsx
  Archivord.UI/src/pages/Home.tsx
  Archivord.UI/src/pages/index.ts
  Archivord.UI/src/services/guilds.service.ts
  Archivord.UI/src/services/user.service.ts
  Archivord.UI/src/vite-env.d.ts
  Archivord.UI/tsconfig.json
  Archivord.UI/tsconfig.node.json
  Archivord.UI/vite.config.ts
Labels: enhancement

#15 Updated README to provide additional information
  ARCHIVORD.API.Docs/openapi.yaml
  README.md
Labels: documentation, enhancement

#17 [API] Fixed self-assignment issue that prevented /channel route from returning any data
  ARCHIVORD.API/src/index.ts
Labels: bug

#18 Fixed GitHub Actions for Readme & Firebase
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .github/workflows/rdme-openapi.yml
Labels: bug
